version: "3.9"
services:
  lamda-resgate-jogos-read:
    build:
      context: ./resgate-jogos-read
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
  lamda-find-all:
    build:
      context: ./resgate-jogos-find-all
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
  lamda-create:
    build:
      context: ./resgate-jogos-create
      dockerfile: Dockerfile
    ports:
      - "9003:8080"