openapi: 3.0.1
info:
  title: Resgaste Jogos
  version: v1
paths:
  /regates:
    post:
      tags:
        - Resgate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResgateBody'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResgateResponse'
    get:
      tags:
        - Resgate
      parameters:
        - name: email
          in: query
          description:  Email de quem solicitou o resgate
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: '#/components/schemas/ResgateResponse'
  /regates/{id}:
    get:
      tags:
        - Resgate
      parameters:
      - name: id
        in: path
        description: ID do resgate
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                   $ref: '#/components/schemas/ResgateResponse'
          
          
components:
  schemas:
    ResgateBody:
      required:
        - usuario
        - jogo
      type: object
      properties:
       usuario:
        type: object
        properties:
          nome:
            type: string
          email: 
            type: string
       jogo:
        type: object
        properties:
          nome: 
            type: string
          descricao:
            type: string
          url_imagem:
            type: string
          genero: 
            type: string
          quantidade: 
            type: number
    ResgateResponse:
      required:
        - usuario
        - jogo
      type: object
      properties:
       usuario:
        type: object
        properties:
          nome:
            type: string
          email: 
            type: string
       jogo:
        type: object
        properties:
          nome: 
            type: string
          descricao:
            type: string
          url_imagem:
            type: string
          genero: 
            type: string
          quantidade: 
            type: number        
       hora:
        type: string
       codigo_resgate:
        type: string
       email_enviado:
        type: string
       _id:
        type: string
  securitySchemes:
    Bearer:
      type: apiKey
      description: Enter 'Bearer' [space] and your token!
      name: Authorization
      in: header
security:
  - Bearer: []
